//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_Full.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public string news_title { get; set; }
        public string news_desc { get; set; }
        public string news_full { get; set; }
        public int news_category { get; set; }
        public string news_img { get; set; }
        public int news_user { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
